<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>174b7647-9390-4528-9fb2-7d8d0ddf3e67</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrackManagement.Application\TrackManagement.Application.csproj" />
    <ProjectReference Include="..\TrackManagement.Infrastructure\TrackManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>
